/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewIssuesRouteImport } from './routes/view-issues'
import { Route as CreateIssueRouteImport } from './routes/create-issue'
import { Route as IssueOwnerRepoNumberRouteImport } from './routes/issue/$owner/$repo/$number'

const ViewIssuesRoute = ViewIssuesRouteImport.update({
  id: '/view-issues',
  path: '/view-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIssueRoute = CreateIssueRouteImport.update({
  id: '/create-issue',
  path: '/create-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueOwnerRepoNumberRoute = IssueOwnerRepoNumberRouteImport.update({
  id: '/issue/$owner/$repo/$number',
  path: '/issue/$owner/$repo/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/create-issue': typeof CreateIssueRoute
  '/view-issues': typeof ViewIssuesRoute
  '/issue/$owner/$repo/$number': typeof IssueOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/create-issue': typeof CreateIssueRoute
  '/view-issues': typeof ViewIssuesRoute
  '/issue/$owner/$repo/$number': typeof IssueOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/create-issue': typeof CreateIssueRoute
  '/view-issues': typeof ViewIssuesRoute
  '/issue/$owner/$repo/$number': typeof IssueOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/create-issue' | '/view-issues' | '/issue/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/create-issue' | '/view-issues' | '/issue/$owner/$repo/$number'
  id:
    | '__root__'
    | '/create-issue'
    | '/view-issues'
    | '/issue/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CreateIssueRoute: typeof CreateIssueRoute
  ViewIssuesRoute: typeof ViewIssuesRoute
  IssueOwnerRepoNumberRoute: typeof IssueOwnerRepoNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view-issues': {
      id: '/view-issues'
      path: '/view-issues'
      fullPath: '/view-issues'
      preLoaderRoute: typeof ViewIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-issue': {
      id: '/create-issue'
      path: '/create-issue'
      fullPath: '/create-issue'
      preLoaderRoute: typeof CreateIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$owner/$repo/$number': {
      id: '/issue/$owner/$repo/$number'
      path: '/issue/$owner/$repo/$number'
      fullPath: '/issue/$owner/$repo/$number'
      preLoaderRoute: typeof IssueOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CreateIssueRoute: CreateIssueRoute,
  ViewIssuesRoute: ViewIssuesRoute,
  IssueOwnerRepoNumberRoute: IssueOwnerRepoNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
